### ISSUE TITLE
Warning: setState(). Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by elie222** [spencercarli/react-native-meteor-boilerplate#21]
I get this warning after logging in on iOS:
`Warning: setState(). Can only update a mounted or mounting component`

**Comment by spencercarli** [comment]
Hmm good catch. @Umar-Abbas would you want to take a look at this?

**Comment by Sivli-Embir** [comment]
+1

**Comment by dvolland** [comment]
+1

**Comment by martwetzels** [comment]
Running into the same issue, anyone managed to solve this? I only get this error when invalid credentials are submitted by Meteor.loginWithPassword()

**Comment by spencercarli** [comment]
Made updates in #39 and didn't see this happening any more. Let me know if that's not the case!

**Comment by dvolland** [comment]
Unfortunately it is still not working for me. I still cant get past creating an account, because I get this message. Updated to the newest version of the boilerplate. Using `react-native: 0.30.0`, `Meteor 1.3.5.1`and `iOS 9.2 Simulator`.

**Comment by elie222** [comment]
This is still happening:
<img width="383" alt="screen shot 2016-07-31 at 11 13 28 am" src="https://cloud.githubusercontent.com/assets/3090527/17275423/e4249194-570f-11e6-9be5-36c0ab616b7b.png">

Why are we using setState at all? I thought you preferred stateless components in your tutorials?

I'm going to be working on this myself now in any case

**Comment by elie222** [comment]
It only happens when signing in with an email address that doesn't exist I believe. But the screen is littered with warnings in any case of all different types.

**Comment by spencercarli** [comment]
Not sure why it's taken me this long to realize but the `setState` error is a result of [this line](https://github.com/spencercarli/react-native-meteor-boilerplate/blob/master/RNApp/app/routes/SignIn/SignInContainer.js#L45) and [this one](https://github.com/spencercarli/react-native-meteor-boilerplate/blob/master/RNApp/app/routes/SignIn/SignInContainer.js#L57).

What's happening is that when you press sign in/up with incorrect values the callback is being handled and setting the error state. The problem here is that when you press login/createAccount you set `Meteor.loggingIn()` to true, thus showing the Loading component.

I'll do some thinking around how to fix this - at least now we know where the problem is originating from!

**Comment by spencercarli** [comment]
@elie222 as for the usage of `setState` - it's being used because I haven't incorporated a library like redux in (intentionally for simplicity's sake). And I typically only use minimongo-cache as read-only.

In an ideal world (like in production apps) we would use a single global store, like Redux, to keep all of our state but that's got a larger learning curve involved.

**Comment by spencercarli** [comment]
Also, @elie222, what other warnings/errors are you seeing? If they're unrelated to this one please open a new issue! I want to make sure everything is working well :smile:

**Comment by spencercarli** [comment]
Should be good to go now 👍

**Comment by elie222** [comment]
Cool. Thanks!

**Comment by elie222** [comment]
I just realised there's still a problem here. Sometimes it shows the error, and sometimes the screen just flashes and the email/password field just go blank with no error message shown.

Seems like the issue is due to what you wrote above:

> What's happening is that when you press sign in/up with incorrect values the callback is being handled and setting the error state. The problem here is that when you press login/createAccount you set Meteor.loggingIn() to true, thus showing the Loading component.

The screen loads, the component gets unmounted, and all state is wiped.

**Comment by elie222** [comment]
My current hacky/fix is changing this line:
  `if (status.connected === false || loggingIn) {`
To:
  `if (status.connected === false) {`
in the main index.js file.

But now you get a flash of the login screen when you open the app and you're logged in, so that's not great either.

**Comment by spencercarli** [comment]
@elie222 opened up a new issue to handle that (since it's slightly different from this) #53
