### ISSUE TITLE
Error on clicking 'Details' button

### ISSUE THREAD

**Issue by naveenkonduru** [spencercarli/react-native-meteor-boilerplate#37]
I just cloned bolierplate and ran the RNapp and metor apps, but after clicking on 'Details' button, I am getting this error below. Hope you will fix it soon.

![image](https://cloud.githubusercontent.com/assets/395769/17028011/b693deba-4f2b-11e6-8416-c8e6abfe50b4.png)

![image](https://cloud.githubusercontent.com/assets/395769/17027966/9804664a-4f2b-11e6-8834-d05c9f5d8c8d.png)

-Naveen.

**Comment by bryanterrell** [comment]
I ran into this and I think the thing that fixed it for me was updating the `react-native-meteor` package. But I went ahead and updated all NPM packages for the RN app and did a `meteor update` for the Meteor app and made some tweaks to remove a couple of deprecation warnings - I created a fork if you want to try it:
https://github.com/bryanterrell/react-native-meteor-boilerplate

I also added `eslint` to the root of the repo just because Atom was complaining without it - I'm sure there's a "right" way to set all that up, but I've had problems with Atom and Visual Studio Code around eslint.

**Comment by spencercarli** [comment]
Should be fixed in #39! Let me know if not!
