### ISSUE TITLE
Transition to react-native-router-flux for routing

### ISSUE THREAD

**Issue by acomito** [spencercarli/react-native-meteor-boilerplate#43]
Have you used or tried to integrate this ever? Or are you just used to navigator?

https://github.com/aksonov/react-native-router-flux

**Comment by spencercarli** [comment]
I haven't tried it in quite a while. The last time I looked at it there were a lot of compatibility issues between React Native versions (I think those have since been solved).

Right now I'm sticking with [`ex-navigator`](https://github.com/exponentjs/ex-navigator) and plan to use [`ex-navigation`](https://github.com/exponentjs/ex-navigation) when the documentation is ready. I've always been impressed by the stuff the Exponent team puts out there - and they're core React Native contributors which adds a little validation to the code they're writing.

**Comment by acomito** [comment]
Hey Spencer I saw [your article](https://medium.com/@spencer_carli/react-native-basics-using-react-native-router-flux-f11e5128aff9#.l2gp9j12n) on react-native-router-flux.

Are you using this more now? Do you plan on adding it to react-native-boilerplate?

I'm trying to decide on a router for my first project. I'm most familiar with vanilla react-router.

**Comment by spencercarli** [comment]
Hey @acomito, definitely something I'm considering - especially since ex-navigator is not being maintained any more.

I'm between `react-native-router-flux` and [`ex-navigation`](https://github.com/exponentjs/ex-navigation), leaning towards the former due to familiarity and popularity.

**Comment by tafelito** [comment]
Hi @spencercarli , I tried to run the RN app, but I cannot get it to work. The `ex-navigation` package is not found when I run npm install. However, I was able to run the app using `react-native-router-flux` but when when doing Account.createUser it's throwing `Method createUser not found` error. I'm not sure if I'm missing anything else, any idea?

Thanks for putting all this together. I've being trying to migrate an meteor app to RN for a while, and this really helped me out. I'm also trying to put together the Facebook login with the Accounts package that is not included at the moment.

**Comment by tafelito** [comment]
@spencercarli So I realized that I forgot to add the accounts-password package in the meteor app. My bad! 😜

**Comment by jamielob** [comment]
@spencercarli - We should keep an eye on @ryanflorence's [react-router](https://github.com/ReactTraining/react-router) - his experiments into using it for RN are  shaping up to be [very interesting](https://twitter.com/ryanflorence)!

**Comment by spencercarli** [comment]
Absolutely. Been watching his teaser videos on Twitter 😄
